[package]
name = "rust-ping-mc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-minecraft-ping = "0.8.0"
libc-strftime = "0.2.0"
serde = "1.0.210"
serde_json = "1.0.128"
structopt = "0.3.26"
tokio = { version = "1.40.0", features = ["rt", "macros", "rt-multi-thread"] }
