[package]
name = "rust-ping-mc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.50"
async-minecraft-ping = "0.8.0"
libc-strftime = "0.2.0"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = { version = "=1.20.0", features = ["rt", "macros", "rt-multi-thread"] }
